### ISSUE TITLE
Mini dataset for testing ideas

### ISSUE THREAD

**Issue by wittawatj** [vincentadam87/gatsby-hackathon-seizure#12]
We definitely need a small-scale data set for quickly testing new preprocessing/features/predictors. The point is that the smaller version should contain characteristics of the big version such that when tested on it, we have a rough idea of what will happen when testing on the big one. The smaller version should also be fixed so that everyone can refer to the same thing. By "small", I mean small enough so that cross validation with combinations of predictors x features can be done in minutes on a local computer (no batch job submission).

**Comment by wittawatj** [comment]
Following the same idea, we may also have medium-sized data set. Fixed so everyone can compare and refer to the same data set. Without this, everybody will need to download 10GB+ data set.

**Comment by vincentadam87** [comment]
@gbohner did a small toy dataset
/nfs/data3/kaggle_prediction_toy
closing for now
